// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPQIkOBpnEKf-nVwtngtzguuLhmySF5xk',
    appId: '1:641150087939:android:c161ca93e9f108e0deef36',
    messagingSenderId: '641150087939',
    projectId: 'spot-rental-pro',
    databaseURL: 'https://spot-rental-pro-default-rtdb.firebaseio.com',
    storageBucket: 'spot-rental-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1SnKB23tKgNSZwjZcgWO0uWH6FuITjlY',
    appId: '1:641150087939:ios:73bbbe6cb422353adeef36',
    messagingSenderId: '641150087939',
    projectId: 'spot-rental-pro',
    databaseURL: 'https://spot-rental-pro-default-rtdb.firebaseio.com',
    storageBucket: 'spot-rental-pro.appspot.com',
    androidClientId: '641150087939-jriae6kpgfhhfcvsnbuu6bg74g3v4lel.apps.googleusercontent.com',
    iosClientId: '641150087939-ri84pmmmr8gaqa0a9jb9dqg7gike1b5i.apps.googleusercontent.com',
    iosBundleId: 'com.m19.spotbuy.soptBuy',
  );
}
